### ISSUE TITLE
grpc-web v1.2.0 appears to be broken

### ISSUE THREAD

**Issue by jfyne** [ngx-grpc/ngx-grpc#10]
Hey,

It looks as though a recent release of `grpc-web` `1.2.0` broke something. This might be it: https://github.com/grpc/grpc-web/issues/865

It might be worth changing the dependencies in this `package.json` to something more specific like `1.1.0` which I believe works.

**Comment by smnbbrv** [comment]
Hi there,

thanks for reporting!

The dependency in package.json is at "peerDependencies", so it does not really force anything; one should be able to use any matching version.

Need to investigate more on what's broken in 1.2.0. This lib doesn't use `Promise` implementation as far as I remember.

**Comment by jfyne** [comment]
When I had 1.2.0 installed I would get a status event with code 0 and then nothing else would come through.

Out of curiosity, why are "peerDependencies" used rather than just a dependency?

**Comment by smnbbrv** [comment]
> When I had 1.2.0 installed I would get a status event with code 0 and then nothing else would come through.

Yep, I see the same on my projects now. Looks like some of their underlying API is changed.

> Out of curiosity, why are "peerDependencies" used rather than just a dependency?

Well, a long story short: in frontend projects in general its better to use peerDependencies over dependencies to avoid client side code duplication (e.g. when you have two projects importing different versions of the same library). In addition, as an end-consumer of the library you can easily override any dependency in "peerDependencies" by installing the one you want; with "dependencies" it is impossible; that's just how npm works. As a downside - the dependencies from "peerDependencies" aren't automatically installed. However, it's better evil :)

**Comment by smnbbrv** [comment]
This issue is a really good one, there are a lot of useful insides described in the connected issue on grpc-web side. 

There is also an upcoming followup fix -> https://github.com/grpc/grpc-web/issues/868 .

Please use latest version that fixes the issue.

**Comment by jfyne** [comment]
@smnbbrv thanks for digging into it, looks like they have been very helpful.
