### ISSUE TITLE
ngx GRPC error Failed parsing HTTP/2 expected 'P' (80) got 'O' (79) at byte 0

### ISSUE THREAD

**Issue by sfariv** [ngx-grpc/ngx-grpc#16]
I have a GRPC server that is working just fine (tested using BloomRPC). and I have a front-end that is built with Angular and ngx-grpc. I am getting the followin error on the server side when sending a request from my grpc client. Any idea what is the problem?

`Complete BDP ping err={"created":"@1600003114.696000000","description":"Failed parsing HTTP/2","file":"d:\a\grpc-node\grpc-node\packages\grpc-native-core\deps\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.cc","file_line":2582,"referenced_errors":[{"created":"@1600003114.696000000","description":"Connect string mismatch: expected 'P' (80) got 'O' (79) at byte 0","file":"d:\a\grpc-node\grpc-node\packages\grpc-native-core\deps\grpc\src\core\ext\transport\chttp2\transport\parsing.cc","file_line":97}]}`

**Comment by sfariv** [comment]
I figured it out. I guess the issue was my lack of knowledge about how ngx-grpc worked.
my grpc server expected a http/2 request, but ngx-grpc was sending a http/1.1 request. so I had to run envoy proxy for that. now the communication is working just fine.

**Comment by smnbbrv** [comment]
That’s how grpc-web works 🙂 this may be changed in the future but now we are forced to have grpc-web proxies...
