### ISSUE TITLE
Error: inject() must be called from an injection context

### ISSUE THREAD

**Issue by tommyngo98** [ngx-grpc/ngx-grpc#17]
Hi, 
I created an simple Angular Library which I then tracked on Bitbucket. I tried to install this library from the bitbucket url with 'npm install {git-repo-url}' and use the dist folder in my application. 

This is the error I get when I want to use my installed library from Bitbucket
![image](https://user-images.githubusercontent.com/33512985/93184122-2b9c8d80-f73c-11ea-908d-4ee294e4c644.png)

This is the folder structure of my library:
![image](https://user-images.githubusercontent.com/33512985/93184348-6acade80-f73c-11ea-8550-f0873bf36d27.png)

 I also used **"preserveSymlinks": true**. It worked once, but then I got the same error back. 

Any idea what might be going wrong / how to fix this?

**Comment by smnbbrv** [comment]
You need to build the library as a normal angular library, this cares of injection for libs

**Comment by smnbbrv** [comment]
Closing as it seems that there is no issue any longer
