### ISSUE TITLE
Question: Configure ngx-grpc in a feature module (lazy loaded)

### ISSUE THREAD

**Issue by hellraisercenobit** [ngx-grpc/ngx-grpc#18]
It seems configuring ngx-grpc inside feature module do not work.
It could be interesting to configure tokens like this instead of app.module (root context) way.
Maybe it is possible but i don't know how :)

**Comment by smnbbrv** [comment]
Hi @hellraisercenobit 

could you add some example code? How would you like to call / configure the things and what exactly is missing / cannot be done?

**Comment by hellraisercenobit** [comment]
Ok no problem,
I mean to configure GRPC_CLIENT_FACTORY or others tokens related to ngx-grpc, it will not work in module context other than application.
It will trigger some errors like:

NullInjectorError: StaticInjectorError[InjectionToken GRPC_CLIENT_FACTORY]:

Router example:

const routes: Route[] = [
  {
    path: '',
    loadChildren: () => import('src/my-lazy-loaded.module').then((m) => m.MyLazyLoadedModule),
  },
];

If we try to configure ngx inside MyLazyLoadedModule it will not work.

**Comment by smnbbrv** [comment]
Wow, never tried that actually, however no bad magic is being performed underneath => it should work... Need to have investigation on this

**Comment by hellraisercenobit** [comment]
Some libraries implements forRoot() or forFeature() methods for module to fix this kind of problems.
I'll do a minimal sample to show you.
It can be really interesting when you need grpc only on a specific module ;)
No need to import everything related to grpc/service/etc... in app.module.

ng build is OK, but at runtime the error is here.

**Comment by hellraisercenobit** [comment]
Seems to be fixed by @Greegko :)
