### ISSUE TITLE
Repeated field doesn't work

### ISSUE THREAD

**Issue by Greegko** [ngx-grpc/ngx-grpc#19]
Found an issue during migration:

Proto:
```
message Random {
  repeated int32 random_values = 1;
}
```

in the generated file we got the following, but during the parsing process the `readInt32` will throw an error.
```ts
      switch (_reader.getFieldNumber()) {
        case 1:
          (_instance.random_values = _instance.random_values || []).push(
            _reader.readInt32()
          );
          break;
```

With `readPackedInt32` function it works like a charm:
```ts
      switch (_reader.getFieldNumber()) {
        case 1:
          _instance.random_values = _reader.readPackedInt32();
          break;
```

Noticed the similar generated code difference for the enums. (got `readEnum()` instead of `readPackedEnum()`)

Not sure about the other fields.

**Comment by paulius-p** [comment]
It's the same for reading all repeated number primitives (enum, bool, int32, int64, float..). Also the same applies when writing - `grpc-web` generated code uses `writePackedxxx`, which is more efficient.

**Comment by smnbbrv** [comment]
Thanks for reporting, already had this problem as well. Please check if everything works fine now.
