### ISSUE TITLE
Setting authentication token for request

### ISSUE THREAD

**Issue by vrao1020** [ngx-grpc/ngx-grpc#26]
What is the correct way to set a bearer token when using this package? I am running into an issue where the request is always failing due to being unauthenticated but works when I test it on a server client (.net grpc client) using the same token. Do note that in both cases, I have a proxy sitting in front of the server for handling the grpc-web request.

```
intercept<Q extends GrpcMessage, S extends GrpcMessage>(request: GrpcRequest<Q, S>, next: GrpcHandler): Observable<GrpcEvent<S>> {
        return this.authService.getTokenSilently$().pipe(
            mergeMap(token => {
                const newMetadata: Metadata = {
                    ...request.requestMetadata,
                    ['Authorization']: `Bearer ${token}`
                };

                const tokenReq = {
                    ...request,
                    requestMetadata: newMetadata
                };
                return next.handle(tokenReq);
            })
        );
    }
```
I am getting an access token and setting is via initializing a new metadata object within a grpc interceptor. I can confirm the interceptor is registered and triggered for each request. I'm not quite sure if this is correct because no matter what I try, the access token is being refused when being set this way. Is there anything I am missing?

**Comment by smnbbrv** [comment]
Hi @vrao1020 

Do you use ConsoleLogger? If yes, when you expand any request in the browser console you will be able to see the metadata in the second row (first row is request data, third row is response data). Can you find the token being set in the metadata?

If no, then your interceptor does not attach the metadata properly.

If yes, then something should be configured on the proxy side. Which grpc-web proxy / implementatiin do you use?

**Comment by vrao1020** [comment]
I am using .Net core with the [Grpc.AspNetCore.Web]((https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1#configure-grpc-web-in-aspnet-core)) package. It's a .Net core only version of what Envoy proxy does. 

I do have console logger enabled and when I have authorization enabled on my server, the call fails with bearer token authorization failing (when called from my angular app).

![image](https://user-images.githubusercontent.com/39545085/94184036-2fc15d00-fe58-11ea-93d3-7692e044212a.png)
Note that the request data is present but everything after is not (the server sends a 401 unauthorized via an OPTIONS response which is odd).

As for the token being set in the metadata, it is because when I removed the authorization requirement from my server, below is the flow when I send a request from my angular app.
![image](https://user-images.githubusercontent.com/39545085/94183977-1ddfba00-fe58-11ea-9f38-deca0383f24a.png)

I used the same token in a console .net core app that uses grpc-web to communicate with the server when authorization is active and receive no errors so I know the token is valid in that regard.

**Comment by smnbbrv** [comment]
OPTIONS response... CORS is in place. What is weird is that the options request fails while it should not have any metadata yet.

We use bearer token exactly in the way you do with the Authorization header in Golang (native client from improbable-eng) and via envoy proxy as well. The only thing we did to make it work was adding to the envoy config the `Authorization` to `Access-Control-Allow-Headers`. 

To me the issue seems to be somewhere in .NET and CORS configuration. Ideally, you should omit CORS whenever possible, it is hard to maintain and always bites the back. It is fairly easy to set a proxy in angular.json for local development and some sort of load balancer to separate the frontend and grpc by some paths and then everything is on the same domain. Probably I should make an example of this in the docs in the future.

**Comment by vrao1020** [comment]
I don't believe CORS is an issue as it works fine when I send the request without trying to authenticate it. My CORS policy also allows any header from specific domains so it can't be that the auth header is being blocked (I inspected request server side without authentication and see the auth header come through). If I have my request setup correctly as you stated, it must be something else on the server side being unable to parse the metadata for the request correctly - I'll open a ticket for that with the library I'm using on the server side to see if I can get anywhere with this. Thanks for your help!

**Comment by smnbbrv** [comment]
You are welcome, hope it gets resolved! Please post the solution if you find it, maybe it helps somebody in the future :)

**Comment by smnbbrv** [comment]
I guess the issue is resolved, feel free to reopen in case not
