### ISSUE TITLE
Bug: proto with Map of message call toObjet in message constructor on javascript object before instanciation

### ISSUE THREAD

**Issue by root14** [ngx-grpc/ngx-grpc#29]
Hi, 

I have a bug with the map of the message below: 

```
message ViewGraphics {
  map<uint64, gxd5.rendering.GraphicElement> elements = 1;
}
```

When my client receive a grpc response, the message is unserialized and give the following error:

`value.elements[k].toObject is not a function`

corresponding in ViewGraphics's constructor generated code to :

(this.elements = _value.elements
            ? Object.keys(_value.elements).reduce((r, k) => (Object.assign(Object.assign({}, r), { [k]: _value.elements[k]
                    ? _value.elements[k].toObject()
                    : undefined })), {})
            : {}),
            ViewGraphics.refineValues(this);

In the ViewGraphics constructor the elements are not yet instanciated so toObject is'nt available. The instanciation of elements is done after the new ViewGraphics so we can't use toObject in constructor on elements.

best regards

**Comment by smnbbrv** [comment]
Hi @root14 

could you please share the message the definition of ` gxd5.rendering.GraphicElement`?

**Comment by root14** [comment]
Hi @smnbbrv ,

thank you to your fast response.

Here the GraphicElement  definition:

```
message GraphicElement {
    uint64 elementId = 1; // unique identifier of the graphic element
    map<uint64, GraphicPoint> points = 2; // list of points of the element
    repeated GraphicPrimitive  primitives = 3; // list of primitives of the element.
    repeated Measure measures = 4; // list of measures of the element
}
```

**Comment by smnbbrv** [comment]
Thx, will try to look at this next week

**Comment by root14** [comment]
Hi @smnbbrv ,

I found this morning that the grpc_worker that i build in a separate project is working with the toObject() call and the generated code. 

I just need to remove the element[k].toObject() function in the ViewGraphic's constructor &  element[k].toObject() in the ViewGraphic's toObject function when i compile the generated ts for my api angular lib and everyting is working.

**Comment by smnbbrv** [comment]
Hi,

looks like the bug should be fixed in dev branch, I plan to do more changes there soon. This can be released in the nearest future, please keep w/ your solution for now
