### ISSUE TITLE
Conflicting message names from packages

### ISSUE THREAD

**Issue by jfyne** [ngx-grpc/ngx-grpc#3]
Hi! Love the project thanks so much for the work.

I have been implementing it into our companies workflow to save us from using the default grpc-web implementations.

One issue I am coming across is conflicting messages in different proto packages. For example:

In lets say `alpha/product.proto` I have
``` proto
syntax = "proto3";

package alpha;

message Product {
    string id = 1;
}
```
And in `beta/product.proto` I have
``` proto
syntax = "proto3";

package beta;

message Product {
    string id = 1;
}
```
Now I am trying to create a library, publish it to npm and then import it into our product sites. So to create a library I am creating a `public-api.ts`
``` typescript
export * from './lib/alpha/product.pb';
export * from './lib/beta/product.pb';
```
 Now this is a problem, since I will get an error
```
Module './lib/alpha/product.pb' has already exported a member 'Product'
```
So here are what I think the options are:

1. Split my `alpha` and `beta` services into separate libraries. This is on the surface the best move, but this becomes a problem when imports get involved. (We have quite a lot of shared constants for example)
2. Somehow namespace the message names with the package.

I have sort of tried 2 by doing this in my `public-api.ts`

``` typescript
import * as alpha from './lib/alpha/product.pb';
import * as beta from './lib/beta/product.pb';

export { alpha, beta }
```
However doing this I end up with an error from angular when im attempting to build an app that imports the library
```
> example-site@0.0.1 build /example-site
> ng build "--prod"


ERROR in app/app.module.ts(48,16): Error during template compile of 'AppModule'
  Unsupported bundled module reference in 'beta'
    'beta' contains the error.
```
This error appears to be to do with the import and export syntax I have used and the way that `aot` compilation handles it.

So really what I am asking for here is just a discussion as to what you think would be the best approach to solve this, without having to rename alll my proto messages to something unique.

Thanks!

**Comment by smnbbrv** [comment]
Hi @jfyne 

thank you for the warm words :) 

You are right, it seems like a problem. The first thing I think of is to take the solution from golang plugin, more precisely this is how they solve similar issue

https://github.com/golang/protobuf#packages-and-input-paths

Maybe we can add similar option `option ng_package = "alpha";` in the beginning of each proto file.

Could this be a potential solution?

**Comment by jfyne** [comment]
Ahhh yes that is a great idea!

What would that do? I'm afraid my typescript knowledge isn't too strong but I am aware that it has namespaces and modules, would perhaps using these give us that encapsulation?

**Comment by smnbbrv** [comment]
@jfyne this would encapsulate every file into a special namespace. Similar to what you've done with

```ts
import * as alpha from './lib/alpha/product.pb';
import * as beta from './lib/beta/product.pb';

export { alpha, beta }
```

However there is one problem with this approach I could think of now. The code becomes non-tree-shakeable. That means all messages and service clients you don't use in your final app will still be included into the result code. And the generated protos are quite big. 

So, actually it's not a good reusable solution. Neither namespace, nor export as sub-objects.

The next idea that comes to mind is to explore the first solution you mention.

> Split my alpha and beta services into separate libraries. This is on the surface the best move, but this becomes a problem when imports get involved. (We have quite a lot of shared constants for example)

In various angular libs there are imports from non-root public apis. E.g. `@angular/material` in the 8th release spits all its modules into separate import paths like `@angular/material/dialog`. What if you do the same? The ng-packagr which is used by `@angular/cli` allows to configure that:

https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md

This remains one library, but meanwhile is being exported separately. Looks like exactly what you need. I haven't tried it but it looks like a valid option to give a try to.

**Comment by jfyne** [comment]
I could try that, however I think there is one blocker to that solution. The relative imports that are generated when you import a definition would not point to the correct file. For example

``` proto
// org/supplier.proto
syntax = "proto3";

package org;

message Supplier {
    string id = 1;
    string name = 2;
}
```

``` proto
// alpha/product.proto
syntax = "proto3";

package alpha;

import "org/supplier.proto";

message Product {
    string id = 1;
    org.Supplier suplier = 2;
}
```

``` proto
// beta/product.proto
syntax = "proto3";

package beta;

import "org/supplier.proto";

message Product {
    string id = 1;
    org.Supplier suplier = 2;
}
```
So now we are importing `Supplier` and using it in the Product messages. The generated code looks something like

``` typescript
import * as org000 from '../org/supplier.pb';
```

So if I were then to move the `alpha`, `beta` and `org` code into there own secondary entrypoints it looks as though the directory structure would have to be (according to this https://stackoverflow.com/a/52558928) something that would break the imports.

Now could the suggested `option ng_package = "alpha"` be used to change those imports into something like

``` proto
// org/supplier.proto
syntax = "proto3";

package org;

option ng_package = "@company/services/org";

message Supplier {
    string id = 1;
    string name = 2;
}
```

``` typescript
import * as org000 from '@company/services/org';
```

**Comment by smnbbrv** [comment]
@jfyne have you found a way to deal with the issue?

**Comment by jfyne** [comment]
@smnbbrv yes.

So I ditched the idea of creating a fully functioning angular library, and instead just created a package which included the output from `protoc-gen-ng`, this means no `public-api.ts`. Ours is called
`@human-made-machine/apis` 

Then when I want to use my package I edit the `tsconfig.app.json` in the root of the project.

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["node_modules/@human-made-machine/apis/**/*", "src/**/*.d.ts"],
  "exclude": ["src/test.ts", "src/**/*.spec.ts"]
}
```
Notice the include line.

Then to use it in my project, for example `src/app/app.module.ts`

```typescript
...
import { GRPC_COMMENTS_CLIENT_SETTINGS } from '@human-made-machine/apis/hmm/classification/comments.pbconf';
...
```
This then prevents the conflicting named classes apart, and if needed I can import them as something else when I need to use them.
