### ISSUE TITLE
Testing gRPC service and messages

### ISSUE THREAD

**Issue by TheMysteriousVincent** [ngx-grpc/ngx-grpc#31]
Is there currently any recommended way to test gRPC services and messages?

**Comment by smnbbrv** [comment]
Hi @TheMysteriousVincent 

the question is whether you really want to test the messages / services because this code is generated; I guess the generator itself should be properly tested instead (which, I must admit, is still not the 100% done).

Isn't simple stubbing the services sufficient enough?

**Comment by TheMysteriousVincent** [comment]
@smnbbrv In general, you are right ofc. But the thing is that I came to a point, where it would be useful to have stub messages and services pre-generated by `ngx-grpc`.

But I guess, I follow your hint and try to implemen that in my repository.

Anyway, thanks for the answer.
