### ISSUE TITLE
Add improbable-eng client support

### ISSUE THREAD

**Issue by RobinKamps** [ngx-grpc/ngx-grpc#32]
I really like this project - it makes grpc for angular so much more convenient.

Can you add a client-wrapper using https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web besides the exxisting grpc-web standard client?
As far as i know @improbable-eng/grpc-web is the only project, that has grpc bi-directional streaming support (over websockets as long as http/2 stream api is not available).

**Comment by smnbbrv** [comment]
Hi @RobinKamps 

this is already on my roadmap.  It requires some breaking changes and concept changes... Anyway, it seems like a long way and it's already in progress.

> As far as i know @improbable-eng/grpc-web is the only project, that has grpc bi-directional streaming support (over websockets as long as http/2 stream api is not available)

They do not provide bi-directional streaming yet (from what I remember) but WebSocket does not have issues with multiple ServerStream requests (while standard grpc-web does, there are issues open on this topic). 

Could you provide an example from them how to use bi-di / client streaming?

**Comment by RobinKamps** [comment]
Thanks for your fast reply.
The docs for a bi-directional stream (js client) are here https://github.com/improbable-eng/grpc-web/tree/master/client/grpc-web .
Besides `grpc.unary` and `grpc.invoke` they have a `grpc.client` wich supports bi-directional streaming - but the transport has to be set to websockets - and the grpc server must support this as well. Websockets for grpc message tunneling is an experimental / workaround feature and will never be in the standard, but there is a proxy https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy for plain grpc servers (which could replace envoy), where you can set a `--use_websockets` flag. 
There are a few projects with different frontend frameworks and backend frameworks out there, wich use improbable grpc client and grpc bi-di streams over websockets - one is https://github.com/johanbrandhorst/grpcweb-example .

**Comment by smnbbrv** [comment]
Perfect, thanks

**Comment by smnbbrv** [comment]
Please check v2.0.0

It's not yet supporting client / bidistreaming, but as I already mentioned this is a long way to go. I have some ideas how to embed it into the current concept, but want to give them more time to mature. I put this info on the README.

For now, I close this issue, because the client is supported

**Comment by ebauman** [comment]
Hi folks - did you mean to publish this under @ngx-grpc on NPM? It appears to be published without the prefix, see https://www.npmjs.com/package/improbable-eng-grpc-web-client

**Comment by smnbbrv** [comment]
Oops, looks like this. I will recheck it asap

**Comment by smnbbrv** [comment]
Please check, the package should be available now

**Comment by ebauman** [comment]
Thanks @smnbbrv looks good.
