### ISSUE TITLE
Params type for new request

### ISSUE THREAD

**Issue by bzvyagintsev** [ngx-grpc/ngx-grpc#37]
I create a new request (`e.g. const req = new TestRequest()`) and try to know type of the message for this request by hovering the mouse over the request name but WebStorm IDE shows only:
```
TestRequest.constructor(     _value?: RecursivePartial<TestRequest>)
Message constructor. Initializes the properties and applies default Protobuf values if necessary
Params:
_value – initial values object or instance of TestRequest to deeply clone from
```

Is it possible to know type of request params by hovering function name in IDE? I can know type only by going inside a constructor of the request or by reading a gRPC service documentation.

**Comment by smnbbrv** [comment]
It looks like `TestRequest` is a message and you are creating a message by `new TestRequest()`. The constructor accepts another instance of `TestRequest` or an object that looks like `TestRequest` or no value. In case you pass one of them and it is a value, all the properties will be deeply cloned and assigned to corresponding properties in this message. So, IDE works quite fine here.

Here is an example of actually running the request with passing the parameters and IDE works as expected as well:

![image](https://user-images.githubusercontent.com/13453858/100785641-3a2c4400-3411-11eb-8a52-ba489a8d942c.png)

**Comment by bzvyagintsev** [comment]
How do you know what object you should pass in a message constructor? For example in `EchoRequest` (`message`, `shouldThrow` and `timestamp`)?

In our case I can see that it is `RecursivePartial<GetMessagesByFolderRequest>` but IDE suggest only methods:
![image](https://user-images.githubusercontent.com/12235087/100797357-0a8e3380-3433-11eb-8b68-7101e8360448.png)

So, I need to go to the constructor or to the documentation to know what params I should pass:
![image](https://user-images.githubusercontent.com/12235087/100797610-75d80580-3433-11eb-8b46-2b5c88776970.png)

**Comment by smnbbrv** [comment]
The first two, that are offered by IDE are in fact getters. Those technically *are methods* but not ordinary ones, they behave like normal properties on the object. What does IDE insert in case you hit enter on let's say `mailbox` getter?

Here is what is displayed in VSCode:

![image](https://user-images.githubusercontent.com/13453858/100843126-2ff26000-347a-11eb-801f-f0355021fa73.png)

**Comment by bzvyagintsev** [comment]
If I choose getter method, IDE inserts the following:
![image](https://user-images.githubusercontent.com/12235087/100883525-7a4aff80-34c1-11eb-9b1a-9aa4f2cb1d78.png)

**Comment by bzvyagintsev** [comment]
I have just tried to use suggestions in VS Code and they work:
![image](https://user-images.githubusercontent.com/12235087/100884966-28a37480-34c3-11eb-887f-59d0ec4205be.png)

Apparently, the question is in the WebStorm.

**Comment by smnbbrv** [comment]
Yes, I think so too.

Probably try to raise the issue at JetBrains team. If you find a way to make it more WebStorm-friendly (maybe some special comment for each getter or similar) please let me know.

**Comment by smnbbrv** [comment]
Hi @bzvyagintsev 

I just had a random idea that might help here. Could you change in the generated code `constructor TestRequest(_value?: RecursivePartial<TestRequest>)` to `constructor TestRequest(_value?: RecursivePartial<TestRequest.AsObject>)` and say whether this resolves the issue? This structure of this object is actually the same as the message but with normally defined properties.

**Comment by bzvyagintsev** [comment]
Hi

This way it works:

![image](https://user-images.githubusercontent.com/12235087/101345445-15642080-3898-11eb-98a7-9999ae9d5853.png)
