### ISSUE TITLE
Stream stops receiving messages after 4 received

### ISSUE THREAD

**Issue by thaibossaw** [ngx-grpc/ngx-grpc#47]
I have a grpc-js server setup with a rpc method called getUsers(). When making the call from the client, I only receive 4 of the messages back, despite there being 6 sent.

Here's the client method:

```
const client = new UsersClient(environment.rpcHost);
    const params = new CMSQuery();
    client.getUsers(params).on('data', (message: User) => {
      const obj = message.toObject();
      console.log(`${obj.name} received`);
      this.users.push(obj);
    }).on('end', () => {
      console.log('End of request');
    });
```

And here's the server method:

```
    async getUsers(call: grpc.ServerWritableStream<CMSQuery, User>): Promise<any> {
        const params = call.request.toObject();
        this.collection.find({}).forEach(user => {
            const message = protoFromObject(User, user);
            call.write(message);
            console.log(`${user.name} sent`);
        }).finally(() => {
            console.log('Closing request');
            call.end();
        });
    }
```

The server has the following console output:

```
User1 sent
User2 sent
User3 sent
User4 sent
User5 sent
User6 sent
Closing Request
```

And yet the client only has the following console output:

```
User1 received
User2 received
User3 received
User4 received
End of request
```

Are there any obvious things that would cause this? Some sort of timeout? Can anyone give me some pointers as to where I should be looking as I'm really stuck at the moment.

Thanks

**Comment by smnbbrv** [comment]
Hi,

sounds like some sort of a timeout.

There are several places you can check: your load balancer, your envoy and finally your server implementation.

The server streaming (unless you use websocket transport from improbable) is implemented as a never ending request (the stream is delivered in chunks until done), so it is affected by any kind of timeout settings on any proxy in between.

**Comment by thaibossaw** [comment]
@smnbbrv thanks for the reply. Ended up debugging through ngcc and found it was an assertion error due to have a too big of integer defined at int32 in the proto file. Changed to int64 and all good now. 

I am indeed using the improbable websocket transport, how would this affect me with longer requests? This is the first time I've used this client so please pardon the basic questions. 

Thanks again for replying.

**Comment by smnbbrv** [comment]
The websocket should not suffer from this I assume. That's a standard implementation issue only. TBH I haven't tried the websocket transport yet, good to know it works 😂

**Comment by thaibossaw** [comment]
@smnbbrv Thanks again.
