### ISSUE TITLE
feature: Make GrpcMessage a generic type.

### ISSUE THREAD

**Issue by dvabuzyarov** [ngx-grpc/ngx-grpc#5]
feature: Make GrpcMessage a generic type.
``` typescript
export interface GrpcMessage<T = unknown> {
  toObject(): T;
  toJSON(): T;
}
```

It will improve type safety. And also wold be a required step to message interfaces.

**Comment by smnbbrv** [comment]
Hi @dvabuzyarov 

there are 2 problems here.

1. `toJSON` and `toObject` could diverge because of the JSON differences for well-known types (e.g. ISOString instead of Timestamp)
2. `toJSON` should probably become a string anyway... 

Just a discussion. What would you think?

**Comment by dvabuzyarov** [comment]
Hi @smnbbrv 
Currently toJSON just calls toObject, so there is no difference and as for me it is not obvious why to have 2 method that do the same.

I am using ngrx and require that all objects passed through it shall be serialisable, so I will use either toJSON or toObject to get a plain object.
