### ISSUE TITLE
Little typo package name

### ISSUE THREAD

**Issue by BernhardBehrendt** [ngx-grpc/ngx-grpc#50]
**Actually:**

`npm i -S @ngx-grpc/improbable-eng-grpc-web @improbable-eng/grpc-web`

**Correct:**

`npm i -S @ngx-grpc/improbable-eng-grpc-web-client @improbable-eng/grpc-web`

**Comment by smnbbrv** [comment]
Hi @BernhardBehrendt 

thanks for reporting the issue
