### ISSUE TITLE
feature: add default client settings

### ISSUE THREAD

**Issue by dvabuzyarov** [ngx-grpc/ngx-grpc#6]
In my project I have only one backend for all proto services and it would be much convenient to setup all services once, as it done in nswag.

```typescript
export const GRPC_SERVICE_DEFAULT_SETTINGS = new InjectionToken<GrpcClientSettings>('GRPC_SERVICE_DEFAULT_SETTINGS');
```

later on a particular service could be 

``` typescript
export class EchoServiceClient {
  private client: GrpcClient;

  constructor(
    @Optional()
    @Inject(GRPC_ECHO_SERVICE_CLIENT_SETTINGS)
    clientSettings: GrpcClientSettings | undefined,
    @Optional()
    @Inject(GRPC_SERVICE_DEFAULT_SETTINGS)
    defaultSettings: GrpcClientSettings | undefined,
    @Inject(GRPC_CLIENT_FACTORY) clientFactory: GrpcClientFactory,
    private handler: GrpcHandler
  ) {
    if (defaultSettings === null && clientSettings === null) {
      throw new Error(
        'Either GRPC_SERVICE_DEFAULT_SETTINGS or GRPC_ECHO_SERVICE_CLIENT_SETTINGS or both should be provided'
      );
    }
    const settings = {
      ...(defaultSettings || {}),
      ...(clientSettings || {})
    } as GrpcClientSettings;
    this.client = clientFactory.createClient('EchoService', settings);
  } 
}
```

**Comment by smnbbrv** [comment]
Hi @dvabuzyarov 

thank you for the proposal.

I already had some thoughts about general gRPC configuration, however did not decide on whether it is super-important to have it vs. the constructor arguments clutter.

Problem is that probably if one wants to make the default config then he also would love to have the per-proto-file config as well. And this already becomes a little bit messy to support on a library level and to understand as end-developer as well.

I would keep it open for now to see how relevant it is to others as well. If yes, we can take it as idea for v1 (when it happens to appear).

**Comment by dvabuzyarov** [comment]
Hi @smnbbrv 

thanks for the answer. 

That makes sense. Anyway I have a project in development where me team decided to try gRPC approach. So I did a new package that is based on your project, so we can test this changes and see what would happen.

**Comment by smnbbrv** [comment]
This is now implemented, see https://github.com/ngx-grpc/ngx-grpc#global-clients-configuration
