### ISSUE TITLE
Bi-directional streaming with @ngx-grpc/grpc-web-client

### ISSUE THREAD

**Issue by teddius** [ngx-grpc/ngx-grpc#86]
Dear forum members, 

we would like to do bi-directional audio streaming from Angular 13 application to backend python grpc server. Any idea how we can accomplish this with ngx-grpc? 

Many thanks for any pointers, example code and your help on this topic!

Best, Andreas

**Comment by smnbbrv** [comment]
Hi, grpc-web does not support client / bidirectional streaming. As stated in the README, the only way to make it work is using @improbable-eng/grpc-web

The example of configuration: https://github.com/ngx-grpc/ngx-grpc#alternative-client-improbable-enggrpc-web

The usage example: https://github.com/ngx-grpc/ngx-grpc#concept
