### ISSUE TITLE
How to reduce timeout or deadline? 

### ISSUE THREAD

**Issue by Barbapapazes** [ngx-grpc/ngx-grpc#92]
Hello,

Is there a way to reduce the timeout (or deadline) time? Actually, it's 30 seconds and way to long for my purpose.

Thanks!

**Comment by smnbbrv** [comment]
Hi, this relates to the client implementation you use. You can however unsubscribe from observable after let's say 10s which would be your desired timeout. Unsubscribe terminates (cancels) the request which is exactly what the timeout would do. You can either do it directly on subscription or use some of rxjs pipes
