### ISSUE TITLE
No licence specified at npm for @ngx-grpc/grpc-web-client

### ISSUE THREAD

**Issue by bratkartoffel** [ngx-grpc/ngx-grpc#94]
Hi,

As tehre is no licence specified on https://www.npmjs.com/package/@ngx-grpc/grpc-web-client, the compliance scan in our company fails. Can you please add the licence (MIT I guess) to the corresponding field?

Thanks,
Simon

![image](https://user-images.githubusercontent.com/1867163/202664497-dd687b14-9fa5-4a25-bd60-c3f590731f00.png)

**Comment by smnbbrv** [comment]
Hallo @bratkartoffel 

should be fixed now, please validate

Schöne Grüße :)
