### ISSUE TITLE
int64 is a string

### ISSUE THREAD

**Issue by damirsaifut** [ngx-grpc/ngx-grpc#95]
Why is int64 generated a string? I studied your code and saw it `const explicitly = implicitlyString.includes(field.type) && field.options.jstype === 2;`

**Comment by smnbbrv** [comment]
JavaScript does not support int64. The maximum possible is 2^53 (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)).

That's nothing special about this library, that's how it is interpreted in any protobuf library in JS.

If you believe your number won't be bigger than int53, you can control this behaviour with a special option:

```protobuf
message dummy { uint64 bigInt = 1; [jstype = JS_NUMBER] }
```

**Comment by damirsaifut** [comment]
> JavaScript не поддерживает int64. Максимально возможное значение — 2^53 (см. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) ).
> 
> В этой библиотеке нет ничего особенного, так она интерпретируется в любой библиотеке protobuf на JS.
> 
> Если вы считаете, что ваше число не будет больше, чем int53, вы можете управлять этим поведением с помощью специальной опции:
> 
> ```proto
> message dummy { uint64 bigInt = 1; [jstype = JS_NUMBER] }
> ```

Can we specify the jstype parameter?

**Comment by smnbbrv** [comment]
yes, it is built-in. Just use it as in example above

**Comment by damirsaifut** [comment]
Thank you so much. Should this be added to the documentation?

**Comment by damirsaifut** [comment]
It doesn't work :( `Expected type name.`

**Comment by smnbbrv** [comment]
could you post what you try? Here are tests and they do work.

https://github.com/ngx-grpc/ngx-grpc/blob/79bba4008ce8f9003912cf4e3e5588a0889459b0/packages/protoc-gen-ng/test/proto/google.proto#L108

https://github.com/ngx-grpc/ngx-grpc/blob/master/packages/protoc-gen-ng/test/proto/jstype.proto

**Comment by damirsaifut** [comment]
I'm sorry. That's my bad. 

Why are all properties in interfaces optional ?

**Comment by smnbbrv** [comment]
https://github.com/ngx-grpc/ngx-grpc#int64
