### ISSUE TITLE
Why are all properties generated in interfaces optional?

### ISSUE THREAD

**Issue by damirsaifut** [ngx-grpc/ngx-grpc#96]
Why are all properties generated in interfaces optional? Some values are not optional. 

```
  export interface AsObject {
    message?: string;
    shouldThrow?: boolean;
    timestamp?: googleProtobuf000.Timestamp.AsObject;
  }
```

proto3
```
message EchoRequest {
  string message = 1;
  bool shouldThrow = 2;
  google.protobuf.Timestamp timestamp = 3;
}
```

**Comment by smnbbrv** [comment]
Hi, that's historically grown like this. There is no real need behind I think. Changing it would make it easier to work in a strict mode...

I currently have no time to change this, but pull requests are very much welcome

**Comment by damirsaifut** [comment]
Hi, I use strict mode.  I'll do that in my spare time.

**Comment by smnbbrv** [comment]
https://github.com/ngx-grpc/ngx-grpc/pull/97
